[server]
host = "localhost"
udp_port_range = "5000 - 6000"
port = 23232
[ssl]
enabled = true
private_key = "/home/hackers/easy-rsa/generated/cert.key"
cert_chain = "/home/hackers/easy-rsa/generated/cert.crt"
[db]
path = '../db'
[auth]
type = "file"
